apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: gitwebhook-operator
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gitwebhook-operator
    app.kubernetes.io/part-of: gitwebhook-operator
    app.kubernetes.io/managed-by: kustomize  
